### ISSUE TITLE
Preprocessor usage in headers causing problems

### ISSUE THREAD

**Issue by akva2** [OPM/opm-autodiff#239]
Preprocessors, templates, headers.. Always fun.
Certain functions (`UgHelpers`) are only compiled if cpgrid is available. That's fine.

Problem happens in downstream modules. They might have cpgrid, while autodiff does not. If the gridhelper is used in the downstream project, you will get linker errors with shared libraries due to the missing symbols in the opm-autodiff library.

Solution would be to differentiate opm-autodiff-has-cp-grid and general has-cpgrid. Alternatively a build system level check and fail if the configurations differ.

**Comment by atgeirr** [comment]
I am closing this issue, it should be resolved since we moved the relevant free function grid helper overloads to dune-cornerpoint (unless I am thinking completely backwards here).

In general I do not think we can aim to support arbitrary differences in configuration across modules (i.e. some with Dune and some without, some with MPI and some without etc.), and I do not see how it could be useful.
