### ISSUE TITLE
ACTION keywords couldn't recognized

### ISSUE THREAD

**Issue by YingfangZhou** [OPM/opm-autodiff#387]
Dear OPM contributor

I was running some simulation using the newest version of OPM (flow_polymer) and found the ACTION keywords couldn't be recognized in the simulator. Is it possible to add some keywords in the simulator by myself? 
Another issue is that the stander output of grid dynamic properties are SWAT, SGAS, SOIL, TEMP, PRESSURE AND TERNARY, is it possible to add more properties (e.g., VOIL, VWAT) in the output file?

Many appreciated your time and help.
Yingfang

**Comment by alfbr** [comment]
Hi Yingfang, you can feed in a custom keyword on the fly using a json scheme, but the simulator will not know what to do with it unless you implement that too. Alternatively patches are vey welcome, so feel free to submit a pull request against opm-parser with the keyword. Unfortunately we do not have a walkthrough on how to add a keyword yet, but it shouldn't be hard if you look at some of the previous pull requests adding other keywords. On the output side, that is in the pipeline, we just have more pressing issues to fix first.

Cheers,
Alf

**Comment by joakim-hove** [comment]
> Is it possible to add some keywords in the simulator by myself? 

Well - that depends. If you have compiled opm-parser yourself you can just add the Json configuration for the `ACTION` keyword in the right folder: https://github.com/OPM/opm-parser/tree/master/opm/parser/share/keywords/000_Eclipse100/A and recompile everything. We have designed the parser so that it should be simple to load external Json files without recompiling - unfortunately some details is missing on that functionality.

**BUT** - adding the Json configuration for the `ACTION` keyword is only so interesting; the `ACTION` keyword implements a quite advanced control mode and implementing that in the OPM code is a much larger job. So although you can quite easily get the `ACTION` keyword into the parser and the output `Deck`, the rest of simulator will still ignore it completely. So my recommendation is actually that you just comment out the `ACTION` keyword from your input file; maybe you can check the actual action of the `ACTION` keyword and implement that in another way.

**Comment by atgeirr** [comment]
I consider this question to be well and clearly answered, and will close the issue. We have no plans to implement ACTION at this time. If anything is unclear feel free to reopen or create a new issue.
