### ISSUE TITLE
Running flow-solvent fails in the Relperm diagnostics

### ISSUE THREAD

**Issue by totto82** [OPM/opm-autodiff#606]
I am not able to run flow-solvent on any of the test cases in solvent_test_suite due to exceptions in the flow diagnostics. "TableContainer does not have any table in the range 0.....0"

**Comment by qilicun** [comment]
@totto82 
This error is because TableManager can not find any saturation function tables in deck file. For solvent, because the the saturation function have different name than blackoil and relperm diagnostics doesn't support that.
To solve this, one way is let relperm diagnostics support solvent model; the other way, this actually is a trick, add a random SOF3 or similar table in solvent input deck....
